### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ClientSide#100]
In order to complete this project, it is required to make a use case diagram for it.

**Comment by agatamrnw** [comment]
![Zrzut ekranu 2023-05-24 155422](https://github.com/Splendor-Mobile-Game/ClientSide/assets/92675107/04f8a8bf-59ab-4854-ba59-a7b9a1978419)
![Zrzut ekranu 2023-05-24 160556](https://github.com/Splendor-Mobile-Game/ClientSide/assets/92675107/e14d6eb8-1a6d-43c9-be35-e4d97887fc1d)

**Comment by agatamrnw** [comment]
![Zrzut ekranu 2023-05-31 000005](https://github.com/Splendor-Mobile-Game/ClientSide/assets/92675107/756e9090-dd84-485f-ba6d-a74caa260ec7)
![Zrzut ekranu 2023-05-31 001054](https://github.com/Splendor-Mobile-Game/ClientSide/assets/92675107/185d74c4-2ad2-454d-8c0c-461c65a0722c)
