### ISSUE TITLE
Update TurnController to properly handle updating the view and button states

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ClientSide#111]
Waiting for:
- #81

The TurnController is responsible for receiving information about the next turn and the current player. However, it currently lacks the functionality to update the view and enable/disable buttons accordingly. 

The following tasks need to be addressed:
1. Disable buttons and cards from being clickable when it's someone else's turn.
2. Enable all buttons when it is our turn to play.

**Comment by KamilDevelopments** [comment]
That is unnecesarry + no time
