### ISSUE TITLE
Implement Content for Tutorial Activity

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ClientSide#116]
To fulfill the project requirement of creating a tutorial for the game, we need to develop the content for the tutorial activity within our application. This issue focuses on adding the necessary instructional materials to provide users with a comprehensive tutorial.

Goals:
- Populate the tutorial activity with informative content, ensuring it covers all essential aspects of the game.

**Comment by KamilDevelopments** [comment]
It was merged
