### ISSUE TITLE
Tokens getter should hide after retrieving successful response

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ClientSide#130]
Currently to get tokens we have to click `TAKE TOKENS` button, choose which tokens we want get from the table and click another button which is also named the same `TAKE TOKENS`, but it's a different button. Then the request is send to the server and we get the response. If this response is successful the layout for taking tokens should hide itself, but currently it stays in its place.

We could also implement the simplest toast after getting the successful response that we actually get tokens successfully. 

![image](https://github.com/Splendor-Mobile-Game/ClientSide/assets/40665452/4b0a1242-3f07-47fa-8ad6-3d8b30fa358f)

**Comment by KamilDevelopments** [comment]
Would be nice to also reset all token values to 0, after turn/taking tokens.
