### ISSUE TITLE
Make some style improvements to the taking tokens layout

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ClientSide#133]
Currently taking tokens take place in the other layout. It's great, but for example a text for black tokens are barely visible. Something can be done about that for sure.

Current state:

![image](https://github.com/Splendor-Mobile-Game/ClientSide/assets/40665452/d6200b02-085e-4a1d-821d-e6913977d202)

**Comment by KamilDevelopments** [comment]
We won't make it
