### ISSUE TITLE
Reserved cards suddenly disappear

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ClientSide#158]
Reserved cards are mysteriously disappearing from the game. One player can see them, while another cannot. The issue occurs even when the second player doesn't need to reserve a card.

**Steps to reproduce:**
1. Start the game.
2. The first player reserves a card.
3. Access the reserved cards; they are visible.
4. Exit the reserved cards view.
5. The second player takes tokens.
6. The reserved cards are not visible for the first player.

Please investigate this issue and provide a resolution.

**Comment by KamilDevelopments** [comment]
<img width="724" alt="Screenshot 2023-05-26 at 15 44 07" src="https://github.com/Splendor-Mobile-Game/ClientSide/assets/50141310/fe089ca2-2430-4e51-b794-f4ae31834722">

I think this is causing the issue. I can fix it in the afternoon.
