### ISSUE TITLE
Acceptance tests UI

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ClientSide#160]
To finish this project, the UI tests must be completed. They should be presented in the form of a table with the following columns: Thing That Is Checked, Expected, and Actual. I must admit, I'm not great at naming things! 🤣

Here's an example:
```
1. 
Thing That Is Checked: Clicked the "RESERVED" button during my turn
Expected: A view with reserved cards should be displayed
Actual: (The view with reserved cards is displayed correctly) / (The view with reserved cards doesn't contain any cards, but it should)

2. 
Thing That Is Checked: Mine cards at the GameActivity screen
Expected: They should be displayed in three columns, each representing a card level (1, 2, 3)
Actual: The requirements have been met
```

Of course, including some images would be necessary. Alternatively, if you have a better idea on how to accomplish this, I'm open to suggestions.

**Comment by patrykcalka** [comment]
Added tests in file. [Testowanie_Wersja_3.pdf](https://github.com/Splendor-Mobile-Game/ClientSide/files/11617899/Testowanie_Wersja_3.pdf)
