### ISSUE TITLE
Acceptance tests Gameplay

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ClientSide#161]
To finish this project, the acceptance tests about the gameplay must be completed. They should be presented in the form of a table with the following columns: Thing That Is Checked, Expected, and Actual. I must admit, I'm not great at naming things! 🤣

Gameplay test should contain at least one game history from the start to the end. It could also contain spontaneous one shot things to check. This tests should not consider the UI as mush as UI tests. You can skip the part, whether something is properly displayed. The important thing is game logic.

Here's an example:
```
1. 
Thing That Is Checked: Creating game as player "Max", room name "Renessaince", and password "123"
Expected: Room with specified parameters created and random enter code
Actual: The requirements have been met

....

// Game started

5. 
Thing That Is Checked: Taking 3 tokens: 1 blue, 1 red, 1 green
Expected: Properly got tokens and change is visible to every player
Actual: The requirements have been met

...
```

Of course, including some images would be necessary. Alternatively, if you have a better idea on how to accomplish this, I'm open to suggestions.

**Comment by Marczewka** [comment]
[GameplayAcceptanceTests.pdf](https://github.com/Splendor-Mobile-Game/ClientSide/files/11635741/GameplayAcceptanceTests.pdf)
