### ISSUE TITLE
Purchasing Reserved Card Results in Buying Opponent's Card

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ClientSide#166]
When attempting to purchase a reserved card in the game, if both the player and the opponent have reserved cards, clicking on the player's reserved card causes the opponent's card to be purchased instead. It appears that there may be a user interface (UI) issue causing this problem, as the player should receive points from their own card and use tokens accordingly.

**Comment by KamilDevelopments** [comment]
Tried to reproduce it, but failed to. I don't think it would be the UI bug, couse even when card info would be displayed wrong you would still need points for buying the different card
