### ISSUE TITLE
Test responsiveness of MainMenu, CreateRoom, JoinRoom and WaitingRoom activities

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ClientSide#55]
Our lecturer has said that it should be tested whether view appropriately scales when viewed on different sized devices with various resolutions and screen aspects. As this is not code it should be documented in `.txt` file or word file of excel file by writing test scenarios. 

Each scenario should have:
- step by step instruction what have you done
- what you expect to happen in positive scenario
- what actually has happened

Test should be executed on running emulators or/and real devices. I put it all into one issue, but you can actually cooperate. I allow max 2 people to work on this.

**Comment by s210897** [comment]
I am adding a pdf file from the responsiveness test of MainMenu, CreateRoom, JoinRoom and WaitingRoom activities @kestivvi 

[test.pdf](https://github.com/Splendor-Mobile-Game/ClientSide/files/11391203/test.pdf)
