### ISSUE TITLE
Find a nice way to manage (create, edit, remove, show) cards from table

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ClientSide#64]
Here's an improved version of your idea with typos and grammar mistakes fixed:

My proposal is as follows:
1. Within the game activity, we will add three Recycler Views for each card tier to display the revealed cards.
2. We will create a class called `RevealedCardsManager` (or something similar) that will contain three adapters for each Recycler View.
3. This class will have three fields with tables for each set of revealed card tiers.
4. These tables will be obtained from the `Game` class, where there are already tables for this purpose (although there may be a need for slight changes in their definitions).
5. The adapters will be notified of any changes to the data set in `UserReaction` classes.

To use a Recycler View, we need to create a layout for the card, a holder class, and an adapter class.

@KamilDevelopments Do you think this is good idea?

**Comment by KamilDevelopments** [comment]
I think, its a very good idea, it's similar to what I have tought. We will also need to think How will do the reserver card option fe. it can also be done in horizontal recyclerView if necessary. With aristocrats we shouldn't have a problem beacouse Theyre only rolled once at the start of the game, so we can just do em mannually.
