### ISSUE TITLE
JoinRoomActivity design

### ISSUE THREAD

**Issue by Vertonowsky** [Splendor-Mobile-Game/ClientSide#8]
## Idea
Server is validating user requests by `enterCode` and `password` properties. We are not going to display all available rooms while inside JoinRoomActivity. 
Instead there should be 2 inputs for `enterCode` and `password` values. 

## TO DO
* Create labels next to inputs
* Add placeholder to inputs similar to `Type here`
* All inputs should have the same width
* Create `Join Game` button
* Add example **response validation** function eg. `private boolean validateResponse()`
* Head to WaitingRoomActivity after successful validation process

**Comment by kestivvi** [comment]
Very good description of what is needed to be done.

**Comment by Vertonowsky** [comment]
Also remember to create an input for user's nickname.

**Comment by KamilDevelopments** [comment]
It should be here or in the starting screen?

**Comment by Vertonowsky** [comment]
here. Same as CreateRoomActivity. User is going to provide his name right before joining room.
