### ISSUE TITLE
Tutorial activity

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ClientSide#92]
One of the requirements for the project is to create a tutorial for the game. I propose that we create the tutorial as an activity within our application, and add a button in the MainMenu to access it.

Goals:
- Create an activity for the tutorial, which can initially be empty or have a basic structure. (*The content will be addressed in another issue*)
- Develop styles for the tutorial activity. (*Another person in the same branch who is proficient in this area can handle this task*)
- Add a button in the MainMenu that will allow users to access the tutorial.
- Ensure that the button is styled appropriately to conform to the MainMenu style. (*Another person in the same branch who is proficient in this area can handle this task*)

**Comment by KamilDevelopments** [comment]
Will probably need 1 person to cut some images with app content fe: AllertDialog with it's options for buying/reserving cards. (it will probably be easier than creating the same layouts again)

**Comment by kestivvi** [comment]
This issue is done. Now it's continued in #116
